### ISSUE TITLE
这一系列教程，GCTT 已经翻译完成 25 个了

### ISSUE THREAD

**Issue by polaris1119** [Tinywan/golang-tutorial#1]
https://studygolang.com/subject/2

如果你是自己翻译，是否没必要做重复的工作。

另外，欢迎加入 GCTT 

https://github.com/studygolang/GCTT

**Comment by polaris1119** [comment]
刚发现你在 GCTT qq 群，但这一系列，好像没看到你有贡献吧。

在 Github 同步更新没问题，不过请保留 GCTT 的签名，以及你在 CSDN 博客上的更新，也请保留 GCTT 的签名，谢谢！

**Comment by Tinywan** [comment]
@polaris1119 `本文由 GCTT 原创翻译，Go语言中文网 首发` 已更新
